version: 0.0
os: linux
files:
  # Copy all files from the artifact to the EC2 instance
  - source: /
    destination: /opt/linkbox-backend
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root