version: 0.0
os: linux
files:
  # Copy scripts to the EC2 instance
  - source: scripts
    destination: /opt/linkbox-backend/scripts
  - source: imagedefinitions.json
    destination: /opt/linkbox-backend/imagedefinitions.json
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root