Description: >
  Ehab / Udacity
  This template deploys the network infrastructure

Parameters:
    EnvironmentName:
        Description: Name tag to apply to resources
        Type: String
        Default: UdacityNetwork
    VpcCIDR:
        Description: CIDR block for the VPC
        Type: String
        Default: 10.0.0.0/16

Resources:
    VPC:
      Type: AWS::EC2::VPC
      Metadata:
        LastUpdated: "2025-10-08" 
      Properties:
        CidrBlock: !Ref VpcCIDR
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName}-VPC
    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName}-IGW
    InternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        InternetGatewayId: !Ref InternetGateway
        VpcId: !Ref VPC
    
Outputs:
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC
  InternetGateway:
    Value: !Ref InternetGateway
    Export:
      Name: !Sub ${EnvironmentName}-IGW
