services:
  db:
    image: postgres:15
    container_name: linkbox-postgres
    environment:
      POSTGRES_DB: linkbox_dev
      POSTGRES_USER: linkbox_user
      POSTGRES_PASSWORD: linkbox_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkbox_user -d linkbox_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: linkbox-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linkbox.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - db
    profiles:
      - tools

volumes:
  postgres_data: